name: Run Trend Scout

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install requests
      - name: Run scout
        env:
          TIKAPI_KEY: ${{ secrets.TIKAPI_KEY }}
        run: python src/scout.py
